### ISSUE TITLE
Micrometer Observation: contextCapture/restore leads to reference cycle when in the same thread

### ISSUE THREAD

**Issue by MartinHeyer** [reactor/reactor-core#3350]
Restoring the ThreadLocals from context to the original thread leads to a reference cycle. The current observation will get itself set as parent. The problem does not occur with subscribeOn(clean thread).

## Expected Behavior
The context observation should just get restored to ThreadLocal.

## Actual Behavior
When subscribing on the original thread having the observation in ThreadLocal already, the observation will get referenced to itself just by calling handle e.g. on the 'next' signal. This can be observed in the debugger. Calling Observation.toString() will give a StackOverflowException.
The observation will stay in the wrong state.
## Steps to Reproduce
test.kt
```kotlin
  @Test
    fun test() {
        val registry = TestObservationRegistry.create()
        val myMono = Mono.just("123")
            .handle { item, sink ->
                val subObs = Observation.createNotStarted("subObservation", registry)
                subObs.observe { logger.info(subObs.toString()) }
                sink.next(item)
            }
            //.subscribeOn(Schedulers.single()) // Works when active

        val obs = Observation.createNotStarted("rootObservation", registry)
        obs.observe {
            myMono
                //.contextWrite { context -> context.put(ObservationThreadLocalAccessor.KEY, obs) } // either way
                .contextCapture() //either way
                .block()
        }
    }
```
## Possible Solution
Simple Workaround: `subscribeOn(someCleanThread)`.

Relevant code:
MonoHandle will call ContextPropagation.contextRestore:
 https://github.com/reactor/reactor-core/blob/3dbc0701a061f7e20e304e0475a5ddac1745bddd/reactor-core/src/main/java/reactor/core/publisher/MonoHandle.java#L44

The chain ends with io.micrometer.observation.contextpropagation.ObservationThreadLocalAccessor.setValue(), which will open a new scope:
https://github.com/micrometer-metrics/micrometer/blob/e205269afd73fe6f87f4640d667495dd9174ee2d/micrometer-observation/src/main/java/io/micrometer/observation/contextpropagation/ObservationThreadLocalAccessor.java#L58

## Your Environment
testImplementation("org.springframework.boot:spring-boot-starter-test:3.+")
(io.projectreactor:reactor-bom:2022.0.2)
implementation("io.projectreactor:reactor:reactor-core:3.5.2)
testImplementation("io.micrometer:micrometer-core:1.10.3")
testImplementation("io.micrometer:micrometer-observation-test:1.10.3")
implementation("io.micrometer:context-propagation:1.0.1")

**Comment by chemicL** [comment]
To my knowledge this issue is fixed in the latest version of Micrometer by the following PRs:

https://github.com/micrometer-metrics/context-propagation/pull/68
https://github.com/micrometer-metrics/micrometer/pull/3613
https://github.com/micrometer-metrics/tracing/pull/152

**Comment by chemicL** [comment]
https://github.com/micrometer-metrics/micrometer/releases/tag/v1.10.4 was just released, it fixes the mentioned issue. Today we will release 3.5.3 of reactor-core which will include https://github.com/micrometer-metrics/context-propagation/releases/tag/v1.0.2 and in combination, this fixes the problem.

**Comment by MartinHeyer** [comment]
@chemicL I might still have a bug using micrometer 1.10.4 and context-propagation 1.-0.2 (can't test using reactor-core:3.5.3 yet). 
Would you like to check before the release?

**Comment by chemicL** [comment]
Thanks for paying attention. Although I was not - the release is already out. Let's discuss in the created issue.
